In [9]:
from moldf import read_mol2
import numpy as np

mol2 = r"C:\Users\evani\OneDrive\Documenten\Phd\RLMD\PDBbind_v2020_refined\refined-set\6fhq\6fhq_ligand.mol2"
ligand_df = read_mol2(mol2)["ATOM"]

In [31]:
def retrieve_coords(df):
        coords = df[["x", "y", "z"]].to_numpy()
        return coords

In [58]:
crds = retrieve_coords(ligand_df)
_l = np.zeros((len(crds),1))
np.hstack((crds, _l))

array([[19.57600021,  2.65400004,  7.86399984,  0.        ],
       [19.35300064,  1.15199995,  8.26000023,  0.        ],
       [19.14500046,  4.50299978,  4.78800011,  0.        ],
       [19.20100021,  2.93199992,  6.56599998,  0.        ],
       [19.28199959,  4.18900013,  6.08400011,  0.        ],
       [19.41399956,  0.91299999,  9.74100018,  0.        ],
       [19.25399971,  5.83199978,  4.50500011,  0.        ],
       [19.49600029,  6.60500002,  5.58500004,  0.        ],
       [19.54999924,  5.63000011,  6.94999981,  0.        ],
       [19.98699951,  3.49600005,  8.68900013,  0.        ],
       [20.13139915,  0.54400003,  7.77589989,  0.        ],
       [18.3635006 ,  0.83819997,  7.89620018,  0.        ],
       [18.86650085,  2.19569993,  5.97779989,  0.        ],
       [19.26399994, -0.0657    ,  9.92980003,  0.        ],
       [18.69939995,  1.4569    , 10.19890022,  0.        ],
       [20.31949997,  1.18729997, 10.08860016,  0.        ],
       [19.15469933,  6.

In [ ]:
env = np.array((100,4))
obs = np.array((100,4))

In [1]:
import torch

In [3]:
torch.zeros((2048,1) + (100,4)).shape

torch.Size([2048, 1, 100, 4])

In [9]:
import torch
from torch.distributions import Normal

# Batch of data with shape [64, 1, 3]
batch_data = torch.randn(64, 3)**2  # Normally distributed random values for example

# Create a normal distribution with mean=0 and std=1
probs = Normal(loc=batch_data, scale=batch_data)

print(batch_data.shape)
action = torch.randn(64,1, 3)**2

# Calculate log_prob for the entire batch
log_probs = probs.log_prob(action)

print(log_probs.shape)


torch.Size([64, 3])
torch.Size([64, 64, 3])


In [11]:
import torch
from torch.distributions import Normal

# Define a batch of means with shape [64, 3]
means = torch.tensor([
    [0.0, 1.0, 2.0]
]*64, dtype=torch.float32)

# If you want to have different standard deviations for each feature/sample
# Here we'll use a common standard deviation, but you can also use a tensor with shape [64, 3]
std_devs = torch.tensor([[1.0, 0.5, 2.0]] * means.shape[0])  # Same std dev for all samples

# Create a Normal distribution using the batch of means
probs = Normal(loc=means, scale=std_devs)

# Example: Generate a batch of data for which we want to calculate log_prob
# Using random samples from the normal distribution for demonstration purposes
batch_data = probs.sample()  # Shape: [64, 3]

# Calculate log_prob for each sample
log_probs = probs.log_prob(batch_data)

# Output log_probs
print("Log Probabilities Shape:", log_probs.shape)  # Should be [64, 3]
print("Log Probabilities:", log_probs)


Log Probabilities Shape: torch.Size([64, 3])
Log Probabilities: tensor([[-1.7683, -0.2289, -1.6149],
        [-4.7913, -3.0241, -1.7321],
        [-1.0119, -0.8573, -2.0196],
        [-1.6901, -0.4033, -2.0291],
        [-0.9864, -0.2594, -3.1952],
        [-0.9323, -0.4795, -5.0946],
        [-0.9910, -1.3582, -1.7105],
        [-1.0154, -0.6440, -1.6886],
        [-2.0493, -0.5410, -1.6638],
        [-0.9549, -1.1894, -2.7361],
        [-1.6296, -0.3257, -1.6884],
        [-1.5803, -1.9507, -1.7105],
        [-2.6788, -3.1944, -1.6744],
        [-1.0101, -0.3454, -1.8789],
        [-0.9380, -0.6140, -1.8398],
        [-1.8215, -0.2857, -1.7600],
        [-1.3941, -1.1513, -1.7401],
        [-1.2301, -0.3242, -1.8067],
        [-0.9244, -0.3098, -2.1738],
        [-1.7560, -1.6635, -2.6090],
        [-1.4929, -2.3824, -1.6655],
        [-1.6736, -0.2782, -1.6128],
        [-0.9281, -0.2472, -2.1129],
        [-0.9200, -0.2337, -2.8576],
        [-1.0440, -0.3204, -4.4654],
        [-1

In [13]:
import numpy as np
np.zeros((1,3))

array([[0., 0., 0.]])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
for 

atom_par H      2.00  0.020   0.0000   0.00051  0.0  0.0  0  -1  -1  3	H   # Non H-bonding Hydrogen
atom_par HD     2.00  0.020   0.0000   0.00051  0.0  0.0  2  -1  -1  3	H   # Donor 1 H-bond Hydrogen
atom_par HS     2.00  0.020   0.0000   0.00051  0.0  0.0  1  -1  -1  3	H   # Donor S Spherical Hydrogen
atom_par C      4.00  0.150  33.5103  -0.00143  0.0  0.0  0  -1  -1  0	C   # Non H-bonding Aliphatic Carbon
atom_par A      4.00  0.150  33.5103  -0.00052  0.0  0.0  0  -1  -1  0	C   # Non H-bonding Aromatic Carbon
atom_par N      3.50  0.160  22.4493  -0.00162  0.0  0.0  0  -1  -1  1	N   # Non H-bonding Nitrogen
atom_par NA     3.50  0.160  22.4493  -0.00162  1.9  5.0  4  -1  -1  1	N   # Acceptor 1 H-bond Nitrogen
atom_par NS     3.50  0.160  22.4493  -0.00162  1.9  5.0  3  -1  -1  1	N   # Acceptor S Spherical Nitrogen
atom_par OA     3.20  0.200  17.1573  -0.00251  1.9  5.0  5  -1  -1  2	O   # Acceptor 2 H-bonds Oxygen
atom_par OS     3.20  0.200  17.1573  -0.00251  1.9  5.0  3  -1  -1  2	O   # Acceptor S Spherical Oxygen
atom_par F      3.09  0.080  15.4480  -0.00110  0.0  0.0  0  -1  -1  4	F   # Non H-bonding Fluorine
atom_par Mg     1.30  0.875   1.5600  -0.00110  0.0  0.0  0  -1  -1  4	Mg  # Non H-bonding Magnesium
atom_par MG     1.30  0.875   1.5600  -0.00110  0.0  0.0  0  -1  -1  4	Mg  # Non H-bonding Magnesium
atom_par P      4.20  0.200  38.7924  -0.00110  0.0  0.0  0  -1  -1  5	P   # Non H-bonding Phosphorus
atom_par SA     4.00  0.200  33.5103  -0.00214  2.5  1.0  5  -1  -1  6	S   # Acceptor 2 H-bonds Sulphur
atom_par S      4.00  0.200  33.5103  -0.00214  0.0  0.0  0  -1  -1  6	S   # Non H-bonding Sulphur
atom_par Cl     4.09  0.276  35.8235  -0.00110  0.0  0.0  0  -1  -1  4	Cl  # Non H-bonding Chlorine
atom_par CL     4.09  0.276  35.8235  -0.00110  0.0  0.0  0  -1  -1  4	Cl  # Non H-bonding Chlorine
atom_par Ca     1.98  0.550   2.7700  -0.00110  0.0  0.0  0  -1  -1  4	Ca  # Non H-bonding Calcium
atom_par CA     1.98  0.550   2.7700  -0.00110  0.0  0.0  0  -1  -1  4	Ca  # Non H-bonding Calcium
atom_par Mn     1.30  0.875   2.1400  -0.00110  0.0  0.0  0  -1  -1  4	Mn  # Non H-bonding Manganese
atom_par MN     1.30  0.875   2.1400  -0.00110  0.0  0.0  0  -1  -1  4	Mn  # Non H-bonding Manganese
atom_par Fe     1.30  0.010   1.8400  -0.00110  0.0  0.0  0  -1  -1  4	Fe  # Non H-bonding Iron
atom_par FE     1.30  0.010   1.8400  -0.00110  0.0  0.0  0  -1  -1  4	Fe  # Non H-bonding Iron
atom_par Zn     1.48  0.550   1.7000  -0.00110  0.0  0.0  0  -1  -1  4	Zn  # Non H-bonding Zinc
atom_par ZN     1.48  0.550   1.7000  -0.00110  0.0  0.0  0  -1  -1  4	Zn  # Non H-bonding Zinc
atom_par Br     4.33  0.389  42.5661  -0.00110  0.0  0.0  0  -1  -1  4	Br  # Non H-bonding Bromine
atom_par BR     4.33  0.389  42.5661  -0.00110  0.0  0.0  0  -1  -1  4	Br  # Non H-bonding Bromine
atom_par I      4.72  0.550  55.0585  -0.00110  0.0  0.0  0  -1  -1  4	I   # Non H-bonding Iodine
atom_par Z      4.00  0.150  33.5103  -0.00143  0.0  0.0  0  -1  -1  0  D   # Non H-bonding covalent map
atom_par G      4.00  0.150  33.5103  -0.00143  0.0  0.0  0  -1  -1  0	D   # Ring closure Glue Aliphatic Carbon  # SF
atom_par GA     4.00  0.150  33.5103  -0.00052  0.0  0.0  0  -1  -1  0	D   # Ring closure Glue Aromatic Carbon   # SF
atom_par J      4.00  0.150  33.5103  -0.00143  0.0  0.0  0  -1  -1  0	D   # Ring closure Glue Aliphatic Carbon  # SF
atom_par Q      4.00  0.150  33.5103  -0.00143  0.0  0.0  0  -1  -1  0	D   # Ring closure Glue Aliphatic Carbon  # SF
atom_par W      0.00  0.200  00.0000  -0.00000  0.0  0.0  0  -1  -1  2	O   # Acceptor 2 H-bonds Oxygen